apiVersion: v1
kind: Service
metadata:
  name: aks-sample-app-service
spec:
  type: LoadBalancer
  selector:
    app: aks-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
